name: CI

on:
  - push
  - pull_request

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/arm64,linux/amd64,linux/arm/v7,linux/riscv64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image for ${{ matrix.platform }}
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
